In [3]:

import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.15.0'

In [4]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

In [5]:
# Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę -
# warstwę gęsto połączoną należy użyć warstwy Dense. Aby dodać warstwę do modelu należy użyć metody .add()
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

In [6]:

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44 (176.00 Byte)
Trainable params: 44 (176.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:

model.add(Dense(units=2))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54 (216.00 Byte)
Trainable params: 54 (216.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
from tensorflow.keras.activations import linear

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -2.619456 -2.619456
1 -2.419997 -2.419997
2 -2.162646 -2.162646
3 -2.006282 -2.006282
4 -1.950249 -1.950249

In [9]:

px.line(data, x='data', y='linear', width=800, range_y=[-2, 2])


In [10]:

from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -2.619456  0.067897
1 -2.419997  0.081660
2 -2.162646  0.103155
3 -2.006282  0.118545
4 -1.950249  0.124526

In [11]:

px.line(data, x='data', y='sigmoid', width=800, range_y=[-0.5, 1.5])

In [12]:

from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()


data  relu
0 -2.619456   0.0
1 -2.419997   0.0
2 -2.162646   0.0
3 -2.006282   0.0
4 -1.950249   0.0

In [13]:
px.line(data, x='data', y='relu', width=800, range_y=[-0.5, 1.5])

In [14]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -2.619456 -0.989444
1 -2.419997 -0.984310
2 -2.162646 -0.973886
3 -2.006282 -0.964469
4 -1.950249 -0.960339

In [15]:
px.line(data, x='data', y='tanh', width=800, range_y=[-1.5, 1.5])


In [16]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97 (388.00 Byte)
Trainable params: 97 (388.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:

# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

In [18]:
# Za dane wejściowe do modelu należy przekazać Numpy arrays:

# epochs - krotność przejścia danych przez sieć w procesie uczenia
# batch_size - rozmiar wsadu po którym następuje aktualizacja wag
# validation_split - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
# validation_data - (x_val, y_val) - dane wykorzystane do walidacji modelu

# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))


In [19]:

data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [20]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
32/32 [==============================] - 1s 3ms/step - loss: 0.8057 - accuracy: 0.5200
Epoch 2/20
32/32 [==============================] - 0s 3ms/step - loss: 0.7134 - accuracy: 0.5830
Epoch 3/20
32/32 [==============================] - 0s 2ms/step - loss: 0.6619 - accuracy: 0.6360
Epoch 4/20
32/32 [==============================] - 0s 2ms/step - loss: 0.6227 - accuracy: 0.6710
Epoch 5/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5904 - accuracy: 0.6980
Epoch 6/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5603 - accuracy: 0.7270
Epoch 7/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5337 - accuracy: 0.7420
Epoch 8/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5084 - accuracy: 0.7740
Epoch 9/20
32/32 [==============================] - 0s 2ms/step - loss: 0.4851 - accuracy: 0.7930
Epoch 10/20
32/32 [==============================] - 0s 2ms/step - loss: 0.4618 - accuracy: 0.8170
Epoch 11/20
32/32 [

In [21]:

model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)

Epoch 1/20
34/34 [==============================] - 1s 4ms/step - loss: 0.7948 - accuracy: 0.5040
Epoch 2/20
34/34 [==============================] - 0s 2ms/step - loss: 0.7063 - accuracy: 0.5560
Epoch 3/20
34/34 [==============================] - 0s 2ms/step - loss: 0.6571 - accuracy: 0.6120
Epoch 4/20
34/34 [==============================] - 0s 2ms/step - loss: 0.6189 - accuracy: 0.6790
Epoch 5/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5870 - accuracy: 0.7120
Epoch 6/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5590 - accuracy: 0.7430
Epoch 7/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5334 - accuracy: 0.7640
Epoch 8/20
34/34 [==============================] - 0s 3ms/step - loss: 0.5077 - accuracy: 0.7950
Epoch 9/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4831 - accuracy: 0.8150
Epoch 10/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4605 - accuracy: 0.8330
Epoch 11/20
34/34 [

In [22]:

data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [23]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

In [24]:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(data,labels, epochs=20)

Epoch 1/20
32/32 [==============================] - 1s 2ms/step - loss: 0.8251 - accuracy: 0.5160
Epoch 2/20
32/32 [==============================] - 0s 2ms/step - loss: 0.7180 - accuracy: 0.5650
Epoch 3/20
32/32 [==============================] - 0s 2ms/step - loss: 0.6678 - accuracy: 0.6000
Epoch 4/20
32/32 [==============================] - 0s 2ms/step - loss: 0.6302 - accuracy: 0.6340
Epoch 5/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5995 - accuracy: 0.6670
Epoch 6/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5730 - accuracy: 0.7100
Epoch 7/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5482 - accuracy: 0.7440
Epoch 8/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5248 - accuracy: 0.7770
Epoch 9/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5015 - accuracy: 0.7970
Epoch 10/20
32/32 [==============================] - 0s 2ms/step - loss: 0.4798 - accuracy: 0.8210
Epoch 11/20
32/32 [

In [25]:
# batch_size=30 - model aktualizowany co 30 próbek

model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)

Epoch 1/20
34/34 [==============================] - 1s 2ms/step - loss: 0.7874 - accuracy: 0.4820
Epoch 2/20
34/34 [==============================] - 0s 2ms/step - loss: 0.7091 - accuracy: 0.5470
Epoch 3/20
34/34 [==============================] - 0s 2ms/step - loss: 0.6636 - accuracy: 0.6080
Epoch 4/20
34/34 [==============================] - 0s 2ms/step - loss: 0.6280 - accuracy: 0.6530
Epoch 5/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5965 - accuracy: 0.6920
Epoch 6/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5690 - accuracy: 0.7260
Epoch 7/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5418 - accuracy: 0.7680
Epoch 8/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5178 - accuracy: 0.7810
Epoch 9/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4937 - accuracy: 0.8160
Epoch 10/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4716 - accuracy: 0.8290
Epoch 11/20
34/34 [

In [28]:
# validation_split=0.2 - wyciąga 20% danych z danych treningowych do procesu walidacji


model = Sequential()
model.add(Dense(units=32, input_shape=(150,), activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, validation_split=0.2, epochs=25)

Epoch 1/25
25/25 [==============================] - 1s 11ms/step - loss: 1.1109 - accuracy: 0.4938 - val_loss: 1.1185 - val_accuracy: 0.4450
Epoch 2/25
25/25 [==============================] - 0s 3ms/step - loss: 0.8855 - accuracy: 0.5038 - val_loss: 0.9997 - val_accuracy: 0.4600
Epoch 3/25
25/25 [==============================] - 0s 4ms/step - loss: 0.7581 - accuracy: 0.5412 - val_loss: 0.9291 - val_accuracy: 0.4400
Epoch 4/25
25/25 [==============================] - 0s 4ms/step - loss: 0.6831 - accuracy: 0.5838 - val_loss: 0.8954 - val_accuracy: 0.4400
Epoch 5/25
25/25 [==============================] - 0s 3ms/step - loss: 0.6351 - accuracy: 0.6363 - val_loss: 0.8795 - val_accuracy: 0.4500
Epoch 6/25
25/25 [==============================] - 0s 4ms/step - loss: 0.5997 - accuracy: 0.6812 - val_loss: 0.8763 - val_accuracy: 0.4350
Epoch 7/25
25/25 [==============================] - 0s 4ms/step - loss: 0.5683 - accuracy: 0.7275 - val_loss: 0.8783 - val_accuracy: 0.4350
Epoch 8/25
25/25 [=

In [29]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=30, batch_size=25, validation_split=0.2, verbose=0)

In [33]:
history = model.fit(data, labels, epochs=30, batch_size=25, validation_split=0.2, verbose=0)

In [35]:
metrics = history.history

In [37]:
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [38]:

test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [44]:
model.predict(test_data).round(4)

1/1 [==============================] - 0s 26ms/step


array([[0.7222],
       [0.599 ],
       [0.7282],
       [0.    ],
       [0.0051]], dtype=float32)

In [50]:
model.predict(test_data).round(0)

1/1 [==============================] - 0s 21ms/step


array([[1.],
       [1.],
       [1.],
       [0.],
       [0.]], dtype=float32)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [51]:

data = np.random.random((1000, 150))
labels = np.random.randint(10, size=(1000, 1))

In [52]:


print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [53]:

data[:3]

array([[0.99278535, 0.80245386, 0.59768828, 0.20440247, 0.33571676,
        0.681158  , 0.47806279, 0.59371674, 0.64220002, 0.0327191 ,
        0.81943206, 0.52479325, 0.55632745, 0.05941606, 0.51421125,
        0.51634438, 0.94292079, 0.24170982, 0.17220687, 0.09100704,
        0.58145588, 0.94863217, 0.51952273, 0.14540425, 0.82392622,
        0.43883125, 0.41507656, 0.70392742, 0.09673557, 0.74883229,
        0.6379996 , 0.97709611, 0.6518093 , 0.54107624, 0.92088081,
        0.15282334, 0.34013806, 0.53372104, 0.85332027, 0.44503682,
        0.59313043, 0.64513895, 0.5237021 , 0.607777  , 0.11603125,
        0.52596468, 0.79274462, 0.43923403, 0.22227132, 0.12965521,
        0.70191303, 0.62020804, 0.60062137, 0.66337854, 0.45530155,
        0.06232317, 0.8573168 , 0.64799526, 0.01650271, 0.47017682,
        0.28426548, 0.06640129, 0.45191041, 0.04374689, 0.64069195,
        0.41579841, 0.80045409, 0.43353588, 0.94709015, 0.54039387,
        0.07769222, 0.11154749, 0.3962612 , 0.66

In [54]:

labels[:10]

array([[4],
       [2],
       [7],
       [2],
       [4],
       [3],
       [8],
       [7],
       [2],
       [0]])

In [55]:

from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [56]:
model = Sequential()
model.add(Dense(units=32, input_shape=(150,), activation='relu'))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 [==============================] - 1s 12ms/step - loss: 2.3933 - accuracy: 0.0800 - val_loss: 2.3465 - val_accuracy: 0.1100
Epoch 2/30
25/25 [==============================] - 0s 3ms/step - loss: 2.3250 - accuracy: 0.0900 - val_loss: 2.3324 - val_accuracy: 0.0950
Epoch 3/30
25/25 [==============================] - 0s 4ms/step - loss: 2.3069 - accuracy: 0.1138 - val_loss: 2.3316 - val_accuracy: 0.1050
Epoch 4/30
25/25 [==============================] - 0s 4ms/step - loss: 2.2962 - accuracy: 0.1262 - val_loss: 2.3379 - val_accuracy: 0.1050
Epoch 5/30
25/25 [==============================] - 0s 4ms/step - loss: 2.2830 - accuracy: 0.1325 - val_loss: 2.3286 - val_accuracy: 0.0850
Epoch 6/30
25/25 [==============================] - 0s 4ms/step - loss: 2.2746 - accuracy: 0.1488 - val_loss: 2.3337 - val_accuracy: 0.0850
Epoch 7/30
25/25 [==============================] - 0s 4ms/step - loss: 2.2545 - accuracy: 0.1637 - val_loss: 2.3514 - val_accuracy: 0.0900
Epoch 8/30
25/25 [=

In [58]:
history.history.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [59]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 52ms/step


array([[0.06828582, 0.05386747, 0.23680809, 0.11631298, 0.07963539,
        0.12870526, 0.10504138, 0.09595513, 0.02749459, 0.08789375],
       [0.05723489, 0.08649801, 0.06657799, 0.19228333, 0.06035289,
        0.13517015, 0.13503204, 0.07709893, 0.09973789, 0.09001388],
       [0.07099004, 0.09073715, 0.09972528, 0.08224081, 0.03290235,
        0.02641393, 0.24376865, 0.08972026, 0.05142967, 0.21207188],
       [0.14486867, 0.07368764, 0.0740893 , 0.15084611, 0.04918456,
        0.11219678, 0.17882423, 0.09181406, 0.04012708, 0.08436143],
       [0.07210384, 0.07353616, 0.11379303, 0.04870201, 0.10416143,
        0.10827538, 0.04731774, 0.135747  , 0.12927781, 0.16708557],
       [0.08179668, 0.07779208, 0.07889845, 0.10102548, 0.16328846,
        0.17113875, 0.09528621, 0.13393506, 0.06971557, 0.02712331],
       [0.05725892, 0.04216522, 0.12021958, 0.11075339, 0.23739271,
        0.11863107, 0.06060383, 0.17114478, 0.04971146, 0.03211898],
       [0.07974105, 0.1760241 , 0.0832709

In [64]:
y_pred = np.argmax(model.predict(test_data), axis=1)

1/1 [==============================] - 0s 25ms/step


In [65]:
y_pred

array([2, 3, 6, 6, 9, 5, 4, 1, 5, 7])

In [66]:

data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000)

In [68]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='linear'))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 [==============================] - 1s 10ms/step - loss: 20.2528 - mse: 599.6009 - val_loss: 17.7400 - val_mse: 478.8558
Epoch 2/30
25/25 [==============================] - 0s 4ms/step - loss: 15.4060 - mse: 364.9102 - val_loss: 14.3312 - val_mse: 305.0617
Epoch 3/30
25/25 [==============================] - 0s 4ms/step - loss: 13.0081 - mse: 243.9325 - val_loss: 13.1969 - val_mse: 233.2634
Epoch 4/30
25/25 [==============================] - 0s 4ms/step - loss: 12.3548 - mse: 210.4612 - val_loss: 12.9779 - val_mse: 220.8396
Epoch 5/30
25/25 [==============================] - 0s 4ms/step - loss: 12.3002 - mse: 206.9923 - val_loss: 12.9724 - val_mse: 220.3273
Epoch 6/30
25/25 [==============================] - 0s 4ms/step - loss: 12.2753 - mse: 206.8176 - val_loss: 12.9646 - val_mse: 219.6646
Epoch 7/30
25/25 [==============================] - 0s 4ms/step - loss: 12.2587 - mse: 205.1406 - val_loss: 12.9721 - val_mse: 220.6694
Epoch 8/30
25/25 [=============================

In [69]:

test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 353ms/step


array([[25.571272],
       [24.253296],
       [24.035227],
       [25.961634],
       [23.844433],
       [25.042662],
       [23.223295],
       [25.116095],
       [22.59284 ],
       [25.504805]], dtype=float32)