In [1]:

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import tensorflow as tf
tf.__version__

'2.15.0'

In [2]:

y_true = 100 + 20 * np.random.randn(50)
y_true


array([ 71.41325686,  97.01848895, 116.36668024,  92.9615703 ,
       121.01474154, 116.00390575, 105.56427331, 106.08356801,
        95.32020679, 100.32873591,  93.59573059,  90.6649135 ,
       151.42263059, 121.56860789, 105.3979035 , 124.08844157,
        68.27909361, 110.52878732, 111.47551534,  60.53456589,
       101.41353257, 119.05613571,  93.52741288, 108.85052362,
        96.76337928, 107.81170443,  81.39957875,  97.23239814,
        82.63309538,  99.93128847,  93.98902711,  89.96662004,
        89.8000621 , 130.00925949,  60.80938897,  89.33180021,
       107.56760964,  86.30034629, 102.01066647,  79.94972212,
        90.64762343,  98.94889753,  87.59372996,  96.0101084 ,
        73.26883131,  81.71976223,  63.76745577,  88.99392794,
        89.09106129,  78.49929364])

In [3]:

y_pred = y_true + 10 * np.random.randn(50)
y_pred

array([ 68.7331246 , 114.27650228, 126.6876178 ,  81.02683696,
       108.416839  , 123.64117675, 103.50688393, 120.83347012,
        80.12268422,  93.19686744,  88.40625988,  90.17699517,
       135.29701017, 112.79845263, 118.11641001, 138.61193923,
        76.15517572, 116.38529156, 122.8695171 ,  64.7293561 ,
       106.94375459, 145.60404823,  82.11384893,  96.79558417,
        87.27351725,  78.71977354,  81.30179429,  82.05268991,
        84.24153964,  92.14516489, 122.78819556, 108.84810657,
        86.75642781, 114.3265182 ,  56.54043431,  81.29511711,
       130.03483159,  90.34897377, 127.72236428, 105.67077707,
       106.12600643,  93.59685251,  69.43917457,  96.111231  ,
        78.61116044,  74.7117062 ,  69.18644975, 108.27937224,
        81.6638534 ,  86.06959106])

In [4]:

results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results.head()

y_true      y_pred
0   71.413257   68.733125
1   97.018489  114.276502
2  116.366680  126.687618
3   92.961570   81.026837
4  121.014742  108.416839

In [5]:

results['error'] = results['y_true'] - results['y_pred']
results.head()

y_true      y_pred      error
0   71.413257   68.733125   2.680132
1   97.018489  114.276502 -17.258013
2  116.366680  126.687618 -10.320938
3   92.961570   81.026837  11.934733
4  121.014742  108.416839  12.597903

In [6]:

def plot_regression_results(y_true, y_pred):
    results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
    min = results[['y_true', 'y_pred']].min().min()
    max = results[['y_true', 'y_pred']].max().max()

    fig = go.Figure(data=[go.Scatter(x=results['y_true'], y=results['y_pred'], mode='markers'),
                    go.Scatter(x=[min, max], y=[min, max])],
                    layout=go.Layout(showlegend=False, width=800,
                                     xaxis_title='y_true',
                                     yaxis_title='y_pred',
                                     title='Regression results'))
    fig.show()
plot_regression_results(y_true, y_pred)

In [7]:

y_true = 100 + 20 * np.random.randn(1000)
y_pred = y_true + 10 * np.random.randn(1000)
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results['error'] = results['y_true'] - results['y_pred']

px.histogram(results, x='error', nbins=50, width=800)

In [8]:

def mean_absolute_error(y_true, y_pred):
    return abs(y_true - y_pred).sum() / len(y_true)

mean_absolute_error(y_true, y_pred)

7.854319874456425

In [9]:
from tensorflow.keras.losses import mean_absolute_error
mean_absolute_error(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=7.854319874456425>

In [15]:
def mean_squared_error(y_true, y_pred):
  return ((y_true-y_pred)**2).sum() / len(y_true)

In [16]:
mean_squared_error(y_true, y_pred)

97.82362758601397

In [17]:

def root_mean_squared_error(y_true, y_pred):
    return np.sqrt(((y_true - y_pred) ** 2).sum() / len(y_true))

root_mean_squared_error(y_true, y_pred)

9.890582772820515

In [18]:

def max_error(y_true, y_pred):
    return abs(y_true - y_pred).max()

In [19]:

max_error(y_true, y_pred)


34.497998353899106

In [20]:

from sklearn.metrics import max_error

max_error(y_true, y_pred)

34.497998353899106

In [21]:

from sklearn.metrics import r2_score

r2_score(y_true, y_pred)

0.7354372238722134

In [22]:

def r2_score(y_true, y_pred):
    numerator = ((y_true - y_pred) ** 2).sum()
    denominator = ((y_true - y_true.mean()) ** 2).sum()
    try:
        r2 = 1 - numerator / denominator
    except ZeroDivisionError:
        print('Dzielenie przez zero')
    return r2

In [23]:

r2_score(y_true, y_pred)

0.7354372238722134